// Generated by scripts/generate-scenario-index.cjs. Do not edit.
import type { ScenarioIndex } from "@lob-sdk/game-data-manager/scenario-index";

export const ww2ScenarioIndex: ScenarioIndex = {
  "fields": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Plains",
        "description": "Smooth rolling hills cut apart by rivers and dotted by various forests and towns, connected together by extensive roads.\n\nMade by Incerus"
      },
      "ru": {
        "name": "Равнина",
        "description": "На усеянной гладкими холмами и прорезанной реками местности рассыпаны леса и здания, соединённые между собой протяжёнными дорогами."
      },
      "es": {
        "name": "Llanuras",
        "description": "Suaves colinas cortadas por ríos y salpicadas por varios bosques y pueblos, conectadas entre sí por extensas carreteras."
      },
      "de": {
        "name": "Ebenen",
        "description": "Glatte Hügel, die von Flüssen durchzogen sind und mit verschiedenen Wäldern und Städten übersät sind, die durch lange Straßen miteinander verbunden sind."
      },
      "fr": {
        "name": "Plaines",
        "description": "Des collines lisses, coupées par des rivières et parsemées de forêts et de villes différentes, reliées entre elles par de longues routes."
      },
      "it": {
        "name": "Pianure",
        "description": "Colline lisce tagliate da fiumi e punteggiate da vari boschi e borghi collegati tra loro da lunghe strade."
      },
      "pl": {
        "name": "Równina",
        "description": "Gładkie wzgórza, poprzecinane rzekami i usiane różnymi lasami i miasteczkami połączonymi ze sobą długimi drogami."
      },
      "ar": {
        "name": "السهول",
        "description": "تقطع التلال الملساء الأنهار وتنتشر فيها غابات وبلدات مختلفة متصلة بطرق طويلة."
      },
      "el": {
        "name": "Πεδιάδα",
        "description": "Ομαλοί λόφοι που διασχίζονται από ποτάμια και είναι διάσπαρτοι με διάφορα δάση και πόλεις που συνδέονται με μεγάλους δρόμους."
      },
      "hi": {
        "name": "मैदानों",
        "description": "चिकनी पहाड़ियों को नदियों के माध्यम से काटा जाता है और लंबी सड़कों से जुड़े विभिन्न जंगलों और कस्बों के साथ बिंदीदार होता है । "
      },
      "hu": {
        "name": "A Síkság",
        "description": "Sima dombok, amelyeket folyók vágnak át, és különböző erdők és városok tarkítják, amelyeket hosszú utak kötnek össze."
      },
      "id": {
        "name": "Dataran",
        "description": "Perbukitan halus yang dilintasi sungai dan dihiasi dengan berbagai hutan dan kota yang dihubungkan oleh jalan yang panjang."
      },
      "ja": {
        "name": "平野",
        "description": "滑らかな丘は川によって切り裂かれ、長い道路で結ばれた様々な森や町が点在しています。"
      },
      "kr": {
        "name": "평원",
        "description": "부드러운 언덕은 강에 의해 절단하고 긴 도로로 연결된 다양한 숲과 마을이 점재."
      },
      "pt": {
        "name": "Planície",
        "description": "Colinas lisas, cortadas por rios e salpicadas de várias florestas e cidades conectadas por longas estradas."
      },
      "tr": {
        "name": "Ovalar",
        "description": "Nehirlerle yarılmış ve çeşitli ormanlarla ve kasabalarla dolu, birbirinden uzun yollarla bağlanmış pürüzsüz tepeler."
      },
      "uk": {
        "name": "Рівнина",
        "description": "Гладкі пагорби, прорізані річками і усіяні різними лісами і містечками, з'єднаними між собою протяжними дорогами."
      },
      "vi": {
        "name": "Đơn giản",
        "description": "Những ngọn đồi mịn màng cắt qua sông và rải rác với nhiều khu rừng và thị trấn được kết nối bởi những con đường dài."
      },
      "zh": {
        "name": "平原",
        "description": "光滑的山丘被河流穿过，点缀着各种森林和由长长的道路连接的城镇。"
      }
    },
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "battle-of-france": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Battle of France",
        "description": "The Battle of France (May–June 1940) was a rapid German victory using Blitzkrieg tactics. Germany bypassed the Maginot Line, defeated Allied forces, evacuated Britain at Dunkirk, and forced France to surrender in six weeks."
      },
      "es": {
        "name": "Batalla de Francia",
        "description": "La Batalla de Francia (mayo-junio de 1940) fue una rápida victoria alemana usando tácticas de Blitzkrieg. Alemania evitó la Línea Maginot, derrotó a las fuerzas aliadas, evacuó a Gran Bretaña en Dunkerque y forzó a Francia a rendirse en seis semanas."
      },
      "fr": {
        "name": "Bataille de France",
        "description": "La bataille de France (mai-juin 1940) fut une victoire allemande rapide utilisant les tactiques de Blitzkrieg. L'Allemagne contourna la ligne Maginot, vainquit les forces alliées, évacua la Grande-Bretagne à Dunkerque et força la France à se rendre en six semaines."
      },
      "de": {
        "name": "Schlacht um Frankreich",
        "description": "Die Schlacht um Frankreich (Mai–Juni 1940) war ein schneller deutscher Sieg mit Blitzkrieg-Taktiken. Deutschland umging die Maginot-Linie, besiegte die alliierten Streitkräfte, evakuierte Großbritannien in Dünkirchen und zwang Frankreich zur Kapitulation in sechs Wochen."
      },
      "ru": {
        "name": "Битва за Францию",
        "description": "Битва за Францию (май–июнь 1940 года) была быстрой немецкой победой с использованием тактики блицкрига. Германские войска обошли линию Мажино и разгромили союзные силы, заставив Великобританию провести эвакуацию из Дюнкерка. Франция капитулировала за шесть недель."
      },
      "pt": {
        "name": "Batalha da França",
        "description": "A Batalha da França (maio–junho de 1940) foi uma rápida vitória alemã usando táticas de Blitzkrieg. A Alemanha contornou a Linha Maginot, derrotou as forças aliadas, evacuou a Grã-Bretanha em Dunquerque e forçou a França a se render em seis semanas."
      },
      "it": {
        "name": "Battaglia di Francia",
        "description": "La battaglia di Francia (maggio–giugno 1940) fu una rapida vittoria tedesca usando tattiche di Blitzkrieg. La Germania aggirò la Linea Maginot, sconfisse le forze alleate, evacuò la Gran Bretagna a Dunkerque e costrinse la Francia ad arrendersi in sei settimane."
      },
      "ja": {
        "name": "フランスの戦い",
        "description": "フランスの戦い（1940年5月〜6月）は、電撃戦戦術を使用したドイツの迅速な勝利でした。ドイツはマジノ線を回避し、連合軍を撃破し、ダンケルクでイギリスを撤退させ、6週間でフランスに降伏を強いました。"
      },
      "kr": {
        "name": "프랑스 전투",
        "description": "프랑스 전투(1940년 5월~6월)는 전격전 전술을 사용한 독일의 빠른 승리였습니다. 독일은 마지노 선을 우회하고, 연합군을 격파하고, 덩케르크에서 영국을 철수시키고, 6주 만에 프랑스에 항복을 강요했습니다."
      },
      "pl": {
        "name": "Bitwa o Francję",
        "description": "Bitwa o Francję (maj–czerwiec 1940) była szybkim zwycięstwem niemieckim wykorzystującym taktykę blitzkriegu. Niemcy ominęły linię Maginota, pokonały siły alianckie, ewakuowały Wielką Brytanię w Dunkierce i zmusiły Francję do kapitulacji w sześć tygodni."
      },
      "tr": {
        "name": "Fransa Muharebesi",
        "description": "Fransa Muharebesi (Mayıs–Haziran 1940), Blitzkrieg taktiklerini kullanan hızlı bir Alman zaferiydi. Almanya Maginot Hattı'nı atladı, Müttefik kuvvetleri yendi, İngiltere'yi Dunkirk'te tahliye etti ve Fransa'yı altı hafta içinde teslim olmaya zorladı."
      },
      "uk": {
        "name": "Битва за Францію",
        "description": "Битва за Францію (травень–червень 1940 року) була швидкою німецькою перемогою з використанням тактики блицкригу. Німеччина обійшла лінію Мажино, розгромила союзні сили, евакуювала Велику Британію в Дюнкерку і змусила Францію капітулювати за шість тижнів."
      },
      "vi": {
        "name": "Trận chiến nước Pháp",
        "description": "Trận chiến nước Pháp (tháng 5–tháng 6 năm 1940) là một chiến thắng nhanh chóng của Đức sử dụng chiến thuật Blitzkrieg. Đức đã vượt qua Phòng tuyến Maginot, đánh bại lực lượng Đồng minh, sơ tán Anh tại Dunkirk và buộc Pháp đầu hàng trong sáu tuần."
      },
      "zh": {
        "name": "法国战役",
        "description": "法国战役（1940年5月至6月）是德国使用闪电战战术取得的快速胜利。德国绕过马奇诺防线，击败了盟军，在敦刻尔克撤离了英国，并在六周内迫使法国投降。"
      },
      "ar": {
        "name": "معركة فرنسا",
        "description": "معركة فرنسا (مايو–يونيو 1940) كانت انتصاراً ألمانياً سريعاً باستخدام تكتيكات الحرب الخاطفة. تجاوزت ألمانيا خط ماجينو، وهزمت قوات الحلفاء، وأجلت بريطانيا في دونكيرك، وأجبرت فرنسا على الاستسلام في ستة أسابيع."
      },
      "hi": {
        "name": "फ्रांस की लड़ाई",
        "description": "फ्रांस की लड़ाई (मई–जून 1940) ब्लिट्जक्रेग रणनीति का उपयोग करके एक त्वरित जर्मन जीत थी। जर्मनी ने मैजिनॉट लाइन को दरकिनार किया, मित्र देशों की सेनाओं को हराया, डनकर्क में ब्रिटेन को खाली कराया, और छह सप्ताह में फ्रांस को आत्मसमर्पण करने के लिए मजबूर किया।"
      },
      "id": {
        "name": "Pertempuran Prancis",
        "description": "Pertempuran Prancis (Mei–Juni 1940) adalah kemenangan cepat Jerman menggunakan taktik Blitzkrieg. Jerman melewati Garis Maginot, mengalahkan pasukan Sekutu, mengevakuasi Inggris di Dunkirk, dan memaksa Prancis menyerah dalam enam minggu."
      },
      "hu": {
        "name": "Franciaország csatája",
        "description": "Franciaország csatája (1940. május–június) egy gyors német győzelem volt, amely villámháború taktikákat használt. Németország megkerülte a Maginot-vonalat, legyőzte a szövetséges erőket, evakuálta Nagy-Britanniát Dunkerque-nél, és hat hét alatt kényszerítette Franciaországot a megadásra."
      },
      "el": {
        "name": "Μάχη της Γαλλίας",
        "description": "Η Μάχη της Γαλλίας (Μάιος–Ιούνιος 1940) ήταν μια γρήγορη γερμανική νίκη χρησιμοποιώντας τακτικές Blitzkrieg. Η Γερμανία παρακάμψε τη Γραμμή Μαζινό, νίκησε τις συμμαχικές δυνάμεις, εκκένωσε τη Βρετανία στο Δουνκέρκη και ανάγκασε τη Γαλλία να παραδοθεί σε έξι εβδομάδες."
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 2160,
      "height": 2160
    }
  },
  "battle-of-moscow": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Battle of Moscow",
        "description": "September 30, 1941. Operation \"Typhoon\" has begun. German tank spearheads are ready to crush the Soviet defenses. However, German time and resources are limited, while the Red Army command intends to hold Moscow at any cost. Will Moscow fall?\n\nA limit of 50 moves or more is highly recommended. - Fat_Jabka, map creator"
      },
      "es": {
        "name": "Batalla de Moscú",
        "description": "30 de septiembre de 1941. Ha comenzado la Operación \"Tifón\". Las puntas de lanza de los tanques alemanes están listas para aplastar las defensas soviéticas. Sin embargo, el tiempo y los recursos alemanes son limitados, mientras que el mando del Ejército Rojo tiene la intención de conservar Moscú a toda costa. ¿Caerá Moscú?\n\nSe recomienda encarecidamente un límite de 50 movimientos o más. - Fat_Jabka, creador del mapa"
      },
      "ru": {
        "name": "Битва за Москву",
        "description": "30 сентября 1941 года. Операция \"Тайфун\" началась. Немецкие танковые клинья готовы сокрушить советскую оборону. Однако, время и ресурсы Германии ограничены, а командование Красной Армии намерено удержать Москву любой ценой . Падёт ли Москва?\n\nРекомендую лимит в 50 ходов. - Fat_Jabka, создатель карты"
      },
      "fr": {
        "name": "Bataille de Moscou",
        "description": "30 septembre 1941. L'opération \"Typhoon\" a commencé. Les coins de chars allemands sont prêts à écraser la défense soviétique. Cependant, le temps et les ressources de l'Allemagne sont limités, et le commandement de l'Armée rouge a l'intention de garder Moscou à tout prix . Moscou tombera-t-il?\n\nJe recommande la limite de 50 coups. - Fat_Jabka, créateur de la carte"
      },
      "de": {
        "name": "Kampf um Moskau",
        "description": "30. September 1941. Die Operation \"Taifun\" hat begonnen. Die deutschen Panzerkeile sind bereit, die sowjetische Verteidigung zu vernichten. Die Zeit und Ressourcen Deutschlands sind jedoch begrenzt, und das Kommando der Roten Armee beabsichtigt, Moskau um jeden Preis zu halten . Wird Moskau fallen?\n\nIch empfehle das Limit von 50 Zügen. - Fat_Jabka, Kartenersteller"
      },
      "uk": {
        "name": "Битва за Москву",
        "description": "30 вересня 1941 року. Операція \"Тайфун\" почалася. Німецькі танкові клини готові розтрощити радянську оборону. Однак, час і ресурси Німеччини обмежені, а командування Червоної Армії має намір утримати Москву за всяку ціну. Чи впаде Москва?\n\nРедкомендую ліміт в 50 ходів. - Fat_Jabka, творець карти"
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 1936,
      "height": 1536
    }
  }
};
