// Generated by scripts/generate-scenario-index.cjs. Do not edit.
import type { ScenarioIndex } from "@lob-sdk/game-data-manager/scenario-index";

export const napoleonicScenarioIndex: ScenarioIndex = {
  "plains": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Plains",
        "description": "Smooth rolling hills cut apart by rivers and dotted by various forests and towns, connected together by extensive roads. Map by usquebaugh."
      },
      "ru": {
        "name": "Равнина",
        "description": "На усеянной гладкими холмами и прорезанной реками местности рассыпаны леса и здания, соединённые между собой протяжёнными дорогами. Карта от usquebaugh."
      },
      "es": {
        "name": "Llanuras",
        "description": "Suaves colinas cortadas por ríos y salpicadas por varios bosques y pueblos, conectadas entre sí por extensas carreteras. Mapa de usquebaugh."
      },
      "de": {
        "name": "Ebenen",
        "description": "Glatte Hügel, die von Flüssen durchzogen sind und mit verschiedenen Wäldern und Städten übersät sind, die durch lange Straßen miteinander verbunden sind. Karte von usquebaugh."
      },
      "fr": {
        "name": "Plaines",
        "description": "Des collines lisses, coupées par des rivières et parsemées de forêts et de villes différentes, reliées entre elles par de longues routes. Carte de usquebaugh."
      },
      "it": {
        "name": "Pianure",
        "description": "Colline lisce tagliate da fiumi e punteggiate da vari boschi e borghi collegati tra loro da lunghe strade. Mappa di usquebaugh."
      },
      "pl": {
        "name": "Równina",
        "description": "Gładkie wzgórza, poprzecinane rzekami i usiane różnymi lasami i miasteczkami połączonymi ze sobą długimi drogami. Mapa autorstwa usquebaugh."
      },
      "ar": {
        "name": "السهول",
        "description": "تقطع التلال الملساء الأنهار وتنتشر فيها غابات وبلدات مختلفة متصلة بطرق طويلة. خريطة من إعداد usquebaugh."
      },
      "el": {
        "name": "Πεδιάδα",
        "description": "Ομαλοί λόφοι που διασχίζονται από ποτάμια και είναι διάσπαρτοι με διάφορα δάση και πόλεις που συνδέονται με μεγάλους δρόμους. Χάρτης από τον usquebaugh."
      },
      "hi": {
        "name": "मैदानों",
        "description": "चिकनी पहाड़ियों को नदियों के माध्यम से काटा जाता है और लंबी सड़कों से जुड़े विभिन्न जंगलों और कस्बों के साथ बिंदीदार होता है । मानचित्र निर्माता: usquebaugh।"
      },
      "hu": {
        "name": "A Síkság",
        "description": "Sima dombok, amelyeket folyók vágnak át, és különböző erdők és városok tarkítják, amelyeket hosszú utak kötnek össze. Készítette: usquebaugh."
      },
      "id": {
        "name": "Dataran",
        "description": "Perbukitan halus yang dilintasi sungai dan dihiasi dengan berbagai hutan dan kota yang dihubungkan oleh jalan yang panjang. Peta oleh usquebaugh."
      },
      "ja": {
        "name": "平野",
        "description": "滑らかな丘は川によって切り裂かれ、長い道路で結ばれた様々な森や町が点在しています。 マップ制作：usquebaugh"
      },
      "kr": {
        "name": "평원",
        "description": "부드러운 언덕은 강에 의해 절단하고 긴 도로로 연결된 다양한 숲과 마을이 점재. 맵 제작: usquebaugh"
      },
      "pt": {
        "name": "Planície",
        "description": "Colinas lisas, cortadas por rios e salpicadas de várias florestas e cidades conectadas por longas estradas. Mapa de usquebaugh."
      },
      "tr": {
        "name": "Ovalar",
        "description": "Nehirlerle yarılmış ve çeşitli ormanlarla ve kasabalarla dolu, birbirinden uzun yollarla bağlanmış pürüzsüz tepeler. Harita: usquebaugh."
      },
      "uk": {
        "name": "Рівнина",
        "description": "Гладкі пагорби, прорізані річками і усіяні різними лісами і містечками, з'єднаними між собою протяжними дорогами. Карта від usquebaugh."
      },
      "vi": {
        "name": "Đơn giản",
        "description": "Những ngọn đồi mịn màng cắt qua sông và rải rác với nhiều khu rừng và thị trấn được kết nối bởi những con đường dài. Bản đồ bởi usquebaugh."
      },
      "zh": {
        "name": "平原",
        "description": "光滑的山丘被河流穿过，点缀着各种森林和由长长的道路连接的城镇。 地图作者：usquebaugh"
      }
    },
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "hills": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Hills",
        "description": "Flat grasslands where tactical battles take place on randomly generated maps. The hills may include patches of forests and scattered buildings, adding strategic depth to unit positioning and gameplay. Map by usquebaugh."
      },
      "ru": {
        "name": "Холмы",
        "description": "Случайно сгенерированная холмистая карта с участками леса и зданиями предлагает стратегическую глубину и тактическое разнообразие игрового процесса. Карта от usquebaugh."
      },
      "ar": {
        "name": "التلال",
        "description": "الأراضي العشبية المسطحة حيث تجري المعارك التكتيكية على خرائط تم إنشاؤها عشوائيا. قد تشمل التلال بقعا من الغابات والمباني المتناثرة ، مما يضيف عمقا استراتيجيا إلى تحديد موقع الوحدة وطريقة اللعب. خريطة من إعداد usquebaugh."
      },
      "de": {
        "name": "Hügel",
        "description": "Flaches Grasland, in dem taktische Schlachten auf zufällig generierten Karten stattfinden. Die Hügel können Waldstücke und verstreute Gebäude enthalten, was der Positionierung und dem Gameplay der Einheiten strategische Tiefe verleiht. Karte von usquebaugh."
      },
      "el": {
        "name": "Λόφους",
        "description": "Επίπεδα λιβάδια όπου πραγματοποιούνται τακτικές μάχες σε τυχαία δημιουργημένους χάρτες. Οι λόφοι μπορεί να περιλαμβάνουν κομμάτια δασών και διάσπαρτα κτίρια, προσθέτοντας στρατηγικό βάθος στην τοποθέτηση και το παιχνίδι της μονάδας. Χάρτης από τον usquebaugh."
      },
      "es": {
        "name": "Colinas",
        "description": "Praderas planas donde se llevan a cabo batallas tácticas en mapas generados aleatoriamente. Las colinas pueden incluir parches de bosques y edificios dispersos, lo que agrega profundidad estratégica al posicionamiento y la jugabilidad de las unidades. Mapa de usquebaugh."
      },
      "fr": {
        "name": "Collines",
        "description": "Prairies plates où des batailles tactiques se déroulent sur des cartes générées aléatoirement. Les collines peuvent inclure des parcelles de forêts et des bâtiments dispersés, ajoutant une profondeur stratégique au positionnement et au gameplay de l'unité. Carte de usquebaugh."
      },
      "hi": {
        "name": "पहाड़ियों",
        "description": "समतल घास के मैदान जहां बेतरतीब ढंग से उत्पन्न मानचित्रों पर सामरिक लड़ाई होती है ।  पहाड़ियों में जंगलों और बिखरी हुई इमारतों के पैच शामिल हो सकते हैं, जो यूनिट पोजिशनिंग और गेमप्ले में रणनीतिक गहराई जोड़ते हैं । मानचित्र निर्माता: usquebaugh।"
      },
      "hu": {
        "name": "Dombok",
        "description": "Sík gyepek, ahol taktikai csaták zajlanak véletlenszerűen generált térképeken. A dombok erdőket és szétszórt épületeket tartalmazhatnak, stratégiai mélységet adva az egység pozícionálásához és a játékmenethez. Készítette: usquebaugh."
      },
      "id": {
        "name": "Bukit",
        "description": "Padang rumput datar tempat pertempuran taktis berlangsung di peta yang dibuat secara acak. Perbukitan mungkin termasuk petak hutan dan bangunan yang tersebar, menambah kedalaman strategis pada posisi unit dan gameplay. Peta oleh usquebaugh."
      },
      "it": {
        "name": "Collina",
        "description": "Praterie piatte dove si svolgono battaglie tattiche su mappe generate casualmente. Le colline possono includere zone di foreste e edifici sparsi, aggiungendo profondità strategica al posizionamento delle unità e al gameplay. Mappa di usquebaugh."
      },
      "ja": {
        "name": "ザ-ヒルズ",
        "description": "ランダムに生成されたマップ上で戦術的な戦いが行われる平らな草原。 丘には森林や散在する建物のパッチが含まれている場合があり、ユニットの配置とゲームプレイに戦略的な深さを追加します。 マップ制作：usquebaugh"
      },
      "kr": {
        "name": "언덕",
        "description": "전술 전투가 무작위로 생성 된지도에서 일어나는 평평한 초원. 언덕에는 숲과 산란한 건물들이 포함될 수 있으며,유닛 위치와 게임 플레이에 전략적 깊이를 더합니다. 맵 제작: usquebaugh"
      },
      "pl": {
        "name": "Wzgórza",
        "description": "Płaskie łąki, na których toczą się bitwy taktyczne na losowo generowanych mapach. Wzgórza mogą zawierać skrawki lasów i rozproszone budynki, dodając strategiczną głębię pozycjonowaniu jednostek i rozgrywce. Mapa autorstwa usquebaugh."
      },
      "pt": {
        "name": "Colinas",
        "description": "Pastagens planas onde as batalhas táticas ocorrem em mapas gerados aleatoriamente. As colinas podem incluir manchas de florestas e edifícios dispersos, adicionando profundidade estratégica ao posicionamento da unidade e jogabilidade. Mapa de usquebaugh."
      },
      "tr": {
        "name": "Tepeler",
        "description": "Taktiksel savaşların rastgele oluşturulan haritalarda gerçekleştiği düz otlaklar. Tepeler, orman parçaları ve dağınık binalar içerebilir; bu da birim konumlandırması ve oynanışa stratejik derinlik katar. Harita: usquebaugh."
      },
      "uk": {
        "name": "Пагорби",
        "description": "Рівнинні луки, на яких відбуваються тактичні битви на випадково згенерованих картах. Пагорби можуть включати ділянки лісів та розкидані будівлі, що надає стратегічну глибину позиціонуванню підрозділів та геймплею. Карта від usquebaugh."
      },
      "vi": {
        "name": "Đồi",
        "description": "Đồng cỏ bằng phẳng nơi các trận chiến chiến thuật diễn ra trên các bản đồ được tạo ngẫu nhiên. Những ngọn đồi có thể bao gồm các mảng rừng và các tòa nhà rải rác, thêm chiều sâu chiến lược để định vị đơn vị và lối chơi. Bản đồ bởi usquebaugh."
      },
      "zh": {
        "name": "山丘",
        "description": "在随机生成的地图上进行战术战斗的平坦草原。 山丘可能包括森林补丁和分散的建筑物，为单位定位和游戏玩法增加了战略深度。 地图作者：usquebaugh"
      }
    },
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "iberia": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Iberia",
        "description": "Fight across the ridges of the Iberian Peninsular"
      },
      "ru": {
        "name": "Иберия",
        "description": "Хребты Пиренейского полуострова замерли в ожидании боя"
      },
      "ar": {
        "name": "ايبيريا",
        "description": "قتال عبر التلال من شبه الجزيرة الايبيرية"
      },
      "de": {
        "name": "Iberia",
        "description": "Kämpfe über die Kämme der Iberischen Halbinsel"
      },
      "el": {
        "name": "Ιβηρία",
        "description": "Καταπολέμηση στις κορυφογραμμές της Ιβηρικής Χερσονήσου"
      },
      "es": {
        "name": "Iberia",
        "description": "Lucha por las cordilleras de la Península Ibérica"
      },
      "fr": {
        "name": "Ibérie",
        "description": "Combattez à travers les crêtes de la péninsule ibérique"
      },
      "hi": {
        "name": "आइबेरिया",
        "description": "इबेरियन प्रायद्वीपीय की लकीरों के पार लड़ो"
      },
      "hu": {
        "name": "Iberia",
        "description": "Küzdelem az Ibériai-félsziget gerincén"
      },
      "id": {
        "name": "Iberia",
        "description": "Bertarung melintasi punggung bukit Semenanjung Iberia"
      },
      "it": {
        "name": "Iberia",
        "description": "Lotta attraverso le creste della penisola iberica"
      },
      "ja": {
        "name": "イベリア",
        "description": "イベリア半島の尾根を越えて戦う"
      },
      "kr": {
        "name": "이베리아",
        "description": "이베리아 반도의 능선을 가로 질러 싸우십시오"
      },
      "pl": {
        "name": "Iberia",
        "description": "Walcz przez grzbiety Półwyspu Iberyjskiego"
      },
      "pt": {
        "name": "Ibéria",
        "description": "Luta através dos cumes da Península Ibérica"
      },
      "tr": {
        "name": "İberya",
        "description": "İber Yarımadası'nın sıradağlarında mücadele edin"
      },
      "uk": {
        "name": "Іберія",
        "description": "Боріться на гірських хребтах Піренейського півострова"
      },
      "vi": {
        "name": "Iberia",
        "description": "Chiến đấu trên các rặng núi Của Bán Đảo Iberia"
      },
      "zh": {
        "name": "伊比利亚",
        "description": "跨越伊比利亚半岛的山脊战斗"
      }
    },
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "tundra": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Tundra",
        "description": "Winter in the flood plain of Polesia. Open snowfields and frozen rivers and lakes provide little succour for weary troops. Quel massacre! Et sans résultat! Map by usquebaugh."
      },
      "ru": {
        "name": "Тундра",
        "description": "Зима в пойме Полесья. Открытые снежные поля, замерзшие реки и озера не дают покоя утомленным войскам. Какое побоище! И без результата! Карта от usquebaugh."
      },
      "es": {
        "name": "Tundra",
        "description": "Invierno en la llanura aluvial de Polesia. Los campos nevados abiertos y los ríos y lagos helados brindan poco consuelo a las tropas fatigadas. ¡Qué masacre! ¡Y sin resultado! Mapa de usquebaugh."
      },
      "de": {
        "name": "Tundra",
        "description": "Winter in der Überschwemmungsebene von Polesia. Offene Schneefelder und gefrorene Flüsse und Seen bieten den müden Truppen wenig Trost. Was für ein Gemetzel! Und ohne Ergebnis! Karte von usquebaugh."
      },
      "fr": {
        "name": "Toundra",
        "description": "L'hiver dans la plaine inondable de la Polésie. Les champs de neige ouverts et les rivières et lacs gelés n'apportent que peu de réconfort aux troupes lassées. Quel massacre ! Et sans résultat ! Carte de usquebaugh."
      },
      "it": {
        "name": "Tundra",
        "description": "L'inverno nella pianura alluvionale della Polesia. I campi di neve aperti e i fiumi e i laghi ghiacciati offrono poco sollievo alle truppe stanche. Quel massacro! E senza risultato! Mappa di usquebaugh."
      },
      "pl": {
        "name": "Tundra",
        "description": "Zima na terenach zalewowych Polesia. Otwarte polach śnieżne oraz zamarznięte rzeki i jeziora dają zmęczonym wojskom niewiele wytchnienia. Co za masakra! I bez rezultatu! Mapa autorstwa usquebaugh."
      },
      "ar": {
        "name": "تندرا",
        "description": "الشتاء في السهول الفيضية في بوليسيا. توفر حقول الثلوج المفتوحة والأنهار والبحيرة المتجمدة القليل من المساعدة للقوات المتعبة. يا له من مجزرة! وبدون نتيجة! خريطة من إعداد usquebaugh."
      },
      "el": {
        "name": "Τούντρα",
        "description": "Χειμώνας στην πλημμυρική πεδιάδα της Πολέσιας. Τα ανοιχτά χιονισμένα πεδία και τα παγωμένα ποτάμια και λίμνες προσφέρουν ελάχιστη ανακούφιση στα κουρασμένα στρατεύματα. Τι σφαγή! Και χωρίς αποτέλεσμα! Χάρτης από τον usquebaugh."
      },
      "hi": {
        "name": "टुंड्रा",
        "description": "पोलिसिया के बाढ़ के मैदान में सर्दी । खुले बर्फबारी और जमी हुई नदियों और झीलों थके हुए सैनिकों के लिए थोड़ा सहारा प्रदान करते हैं । क्या नरसंहार! और बिना परिणाम के! मानचित्र निर्माता: usquebaugh।"
      },
      "hu": {
        "name": "Tundra",
        "description": "Tél Poleszje ártéri síkságán. A nyílt hófödte mezők, a befagyott folyók és tavak nem sok enyhülést nyújtanak a fáradt csapatoknak. Micsoda mészárlás! És eredmény nélkül! Készítette: usquebaugh."
      },
      "id": {
        "name": "Tundra",
        "description": "Musim dingin di dataran banjir Polesia. Padang salju yang terbuka serta sungai dan danau yang membeku memberikan sedikit pertolongan bagi pasukan yang lelah. Pembantaian yang luar biasa! Dan tanpa hasil! Peta oleh usquebaugh."
      },
      "ja": {
        "name": "ツンドラ",
        "description": "ポレシアの氾濫原の冬。開いた雪原と凍った川や湖は、疲れた軍隊にほとんど救いを与えません。なんて虐殺なんだ！そして何の結果も得られない！ マップ制作：usquebaugh"
      },
      "kr": {
        "name": "툰드라",
        "description": "Polesia의 홍수 평야의 겨울. 열린 설원과 얼어 붙은 강과 호수는 지친 군대에게 거의 도움을주지 않습니다. 참으로 대학살이다! 그리고 아무 결과도 없다! 맵 제작: usquebaugh"
      },
      "pt": {
        "name": "Tundra",
        "description": "O inverno na planície aluvial da Polésia. Os campos de neve abertos e os rios e lagos gelados oferecem pouco alívio para as tropas cansadas. Que massacre! E sem resultado! Mapa de usquebaugh."
      },
      "tr": {
        "name": "Tundra",
        "description": "Polesia sel ovasında kış. Açık kar alanları ve donmuş nehirler ile göller yorgun birliklere çok az yardım sağlar. Ne katliam ama! Ve sonuçsuz! Harita: usquebaugh."
      },
      "uk": {
        "name": "Тундра",
        "description": "Зима в заплаві Полісся. Відкриті снігові поля та замерзлі річки й озера дають мало спокою втомленим військам. Яке побоїще! І без результату! Карта від usquebaugh."
      },
      "vi": {
        "name": "Tundra",
        "description": "Mùa đông ở vùng ngập mặn của Polesia. Những cánh đồng tuyết rộng lớn và sông hồ đóng băng cung cấp rất ít sự hỗ trợ cho quân đội mệt mỏi. Một cuộc thảm sát thật sự! Và không có kết quả! Bản đồ bởi usquebaugh."
      },
      "zh": {
        "name": "苔原",
        "description": "波列西亚平原的冬天。开阔的雪地、冰封的河流和湖泊为疲惫不堪的部队提供的救援微乎其微。多么惨烈的屠杀！而且毫无结果！ 地图作者：usquebaugh"
      }
    },
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "city": {
    "name": "City",
    "description": "A city stands near the field of battle.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "hedgerows": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Hedgerows",
        "description": "Chaotic, clausterphobic farms hemmed in by hedges on every side."
      },
      "ru": {
        "name": "Бокажи",
        "description": "Высокие живые изгороди со всех сторон огораживают хаотично расположенные поля."
      },
      "ar": {
        "name": "سياج",
        "description": "مزارع فوضوية خانقة محاطة بتحوطات من كل جانب."
      },
      "de": {
        "name": "Hecke",
        "description": "Chaotische, klausterphobische Farmen, die auf allen Seiten von Hecken gesäumt sind."
      },
      "el": {
        "name": "Φράχτες",
        "description": "Χαοτικές, κλαουστερφοβικές φάρμες που περιβάλλονται από φράκτες από κάθε πλευρά."
      },
      "es": {
        "name": "Setos",
        "description": "Granjas caóticas y claustrofóbicas rodeadas de setos por todos lados."
      },
      "fr": {
        "name": "Haies",
        "description": "Des fermes chaotiques et clausterphobes entourées de haies de tous côtés."
      },
      "hi": {
        "name": "हेडगेवार",
        "description": "अराजक, क्लॉस्टरफोबिक खेतों को हर तरफ हेजेज द्वारा घेर लिया गया ।"
      },
      "hu": {
        "name": "Sövény",
        "description": "Kaotikus, klausterfóbiás gazdaságok sövényekkel szegélyezve minden oldalon."
      },
      "id": {
        "name": "Pagar tanaman",
        "description": "Peternakan yang kacau dan sesak dikelilingi oleh pagar tanaman di setiap sisinya."
      },
      "it": {
        "name": "Siepe",
        "description": "Fattorie caotiche e claustrofobiche circondate da siepi su ogni lato."
      },
      "ja": {
        "name": "生け垣",
        "description": "混沌とした農場はあらゆる側のヘッジによって縁取られました。"
      },
      "kr": {
        "name": "울타리",
        "description": "혼란스럽고 폐쇄적인 농장은 모든 쪽에서 울타리로 둘러싸여 있습니다."
      },
      "pl": {
        "name": "Żywopłoty",
        "description": "Chaotyczne, klausterfobiczne farmy otoczone żywopłotami z każdej strony."
      },
      "pt": {
        "name": "Sebes",
        "description": "Fazendas caóticas e clausterfóbicas cercadas por sebes de todos os lados."
      },
      "tr": {
        "name": "Çitli tarlalar",
        "description": "Her tarafı çitlerle çevrili, kaotik ve dar alanlı çiftlikler."
      },
      "uk": {
        "name": "Живопліт",
        "description": "Хаотичні ферми, що викликають клаустрофобію, оточені з усіх боків живоплотами."
      },
      "vi": {
        "name": "Hàng rào",
        "description": "Các trang trại hỗn loạn, ngột ngạt được bao bọc bởi hàng rào ở mọi phía."
      },
      "zh": {
        "name": "树篱",
        "description": "混乱的、令人厌烦的农场被两边的树篱围住了."
      }
    },
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "low-countries": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Low Countries",
        "description": "Battle through the canals of the low countries."
      },
      "ru": {
        "name": "Нижние Земли",
        "description": "Поле боя преграждено извитыми каналами Нидерландов."
      },
      "ar": {
        "name": "البلدان المنخفضة",
        "description": "معركة من خلال قنوات البلدان المنخفضة"
      },
      "de": {
        "name": "Niedrige Länder",
        "description": "Kämpfe dich durch die Kanäle der Niederlande."
      },
      "el": {
        "name": "Κάτω Χώρες",
        "description": "Μάχη μέσα από τα κανάλια των Κάτω Χωρών."
      },
      "es": {
        "name": "Países Bajos",
        "description": "Lucha a través de los canales de los países bajos."
      },
      "fr": {
        "name": "Pays - Bas",
        "description": "Bataille à travers les canaux des Pays-bas."
      },
      "hi": {
        "name": "निम्न देश",
        "description": "निम्न देशों की नहरों के माध्यम से लड़ाई ।"
      },
      "hu": {
        "name": "Alacsony Országok",
        "description": "Csata az alacsony országok csatornáin keresztül."
      },
      "id": {
        "name": "Negara-negara Rendah",
        "description": "Pertempuran melalui kanal-kanal di negara-negara dataran rendah."
      },
      "it": {
        "name": "Paesi bassi",
        "description": "Battaglia attraverso i canali dei paesi bassi."
      },
      "ja": {
        "name": "低い国",
        "description": "低い国の運河を通って戦います"
      },
      "kr": {
        "name": "낮은 국가",
        "description": "낮은 국가의 운하를 통해 전투."
      },
      "pl": {
        "name": "Kraje Niskie",
        "description": "Walcz kanałami Niderlandów."
      },
      "pt": {
        "name": "Países Baixos",
        "description": "Batalha através dos canais dos Países Baixos."
      },
      "tr": {
        "name": "Alçak Ülkeler",
        "description": "Alçak ülkelerin kanallarında mücadele edin."
      },
      "uk": {
        "name": "Нідерланди",
        "description": "Боріться по каналах Нідерландів."
      },
      "vi": {
        "name": "Các Nước Thấp",
        "description": "Chiến đấu qua các kênh đào của các nước thấp."
      },
      "zh": {
        "name": "低的国家",
        "description": "通过低地国家的运河战斗。"
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "lake": {
    "name": "Lake",
    "description": "A scenic landscape featuring a large central lake with organic shorelines and natural depth variation. The terrain includes lush forests and gentle hills surrounding the water feature.",
    "ranked": true,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "black-forest": {
    "name": "Black Forest",
    "description": "A dense forest with a few small lakes.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": null
  },
  "silva-sanctorum": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Silva Sanctorum",
        "description": "A claustrophobic battle amidst the hedgerows. Designed by Discord user and top player EvictedSaint."
      },
      "ru": {
        "name": "Храм Сильвы",
        "description": "Эта гибридная карта со множеством закрытых живыми изгородями участков создана одним из лучших игроков и участником сервера Discord игры EvictedSaint."
      },
      "ar": {
        "name": "سيلفا سانكتوروم",
        "description": "معركة خانقة وسط السياج. صممه Discord وأفضل لاعب EvictedSaint."
      },
      "de": {
        "name": "Silva Sanctorum",
        "description": "Eine klaustrophobische Schlacht inmitten der Hecken. Entworfen von Discord-Benutzer und Top-Spieler EvictedSaint."
      },
      "el": {
        "name": "Σίλβα Σανκτόρουμ",
        "description": "Μια κλειστοφοβική μάχη ανάμεσα στους φράκτες. Σχεδιασμένο από τον χρήστη Discord και τον κορυφαίο παίκτη EvictedSaint."
      },
      "es": {
        "name": "Silva Sanctorum",
        "description": "Una batalla claustrofóbica en medio de los setos. Diseñado por el usuario de Discord y mejor jugador EvictedSaint."
      },
      "fr": {
        "name": "Silva Sanctorum",
        "description": "Une bataille claustrophobe au milieu des haies. Conçu par l'utilisateur Discord et le meilleur joueur EvictedSaint."
      },
      "hi": {
        "name": "सिल्वा सैंक्टोरम",
        "description": "हेजर्स के बीच एक क्लॉस्ट्रोफोबिक लड़ाई ।  डिस्कॉर्ड उपयोगकर्ता और शीर्ष खिलाड़ी बेदखल संत द्वारा डिज़ाइन किया गया ।"
      },
      "hu": {
        "name": "Silva Sanctorum",
        "description": "Klausztrofóbiás csata a sövények között. Tervezte Discord felhasználó és a legjobb játékos EvictedSaint."
      },
      "id": {
        "name": "Silva Sanctorum",
        "description": "Pertempuran sesak di tengah pagar tanaman. Dirancang oleh pengguna Discord dan pemain top EvictedSaint."
      },
      "it": {
        "name": "Silva Sanctorum",
        "description": "Una battaglia claustrofobica tra le siepi. Progettato da Discord utente e top player EvictedSaint."
      },
      "ja": {
        "name": "シルバ-サンクトルム",
        "description": "生け垣の中の閉所恐怖症の戦い。 Discordユーザーとトッププレーヤーによって設計されたEvictedSaint。"
      },
      "kr": {
        "name": "실바 산크토럼",
        "description": "울타리 속에서 밀실 공포증 전투. 불화 사용자 및 최고의 플레이어가 디자인했습니다."
      },
      "pl": {
        "name": "Silva Sanctorum",
        "description": "Klaustrofobiczna Bitwa pośród żywopłotów. Zaprojektowany przez użytkownika Discord i najlepszego gracza EvictedSaint."
      },
      "pt": {
        "name": "Silva Sanctorum",
        "description": "Uma batalha claustrofóbica entre as sebes. Projetado pelo usuário do Discord e melhor jogador EvictedSaint."
      },
      "tr": {
        "name": "Silva Sanctorum",
        "description": "Çalılıklar arasında klostrofobik bir mücadele. Discord kullanıcısı ve üst düzey oyuncu EvictedSaint tarafından tasarlandı."
      },
      "uk": {
        "name": "Святилище Сільви",
        "description": "Викликає клаустрофобію бій серед живоплотів. Розроблено Користувачем Discord та найкращим гравцем EvictedSaint."
      },
      "vi": {
        "name": "Silva Sanctorum",
        "description": "Một trận chiến ngột ngạt giữa hàng rào. Được thiết kế bởi Người Dùng Discord và người chơi Hàng đầu EvictedSaint."
      },
      "zh": {
        "name": "席尔瓦圣所",
        "description": "一场在树篱中幽闭恐怖的战斗。 由Discord用户和顶级玩家EvictedSaint设计。"
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 2000,
      "height": 1800
    }
  },
  "andes-and-valley": {
    "name": "Andes & Valley",
    "description": "Andes Valley: a narrow pass between mountains marked by a raging river. Along its banks lie small villages and farms that sustain life in the valley. A finely balanced battlefield where no army holds the advantage of terrain.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1804,
      "height": 1612
    }
  },
  "lines-of-legends": {
    "name": "Lines of Legends",
    "description": "Welcome to MOBA-LOB!",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1600,
      "height": 1600
    }
  },
  "river-valley": {
    "name": "Valley Cruz St-Mère",
    "description": "Created by Discord user SForSikeo.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1904,
      "height": 1512
    }
  },
  "saand-lakes": {
    "name": "Sa'and Lakes",
    "description": "Fight among a ring of lakes and creeks, but be mindful of the strategic heights. Made by Discord User MooPro127.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "faucon-river-valley": {
    "name": "Faucon River Valley",
    "description": "Duke it out on both banks of a winding river valley and conquer a ring of strategic hills. Designed by veteran player and Discord member Hawke.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "amnis-nucum": {
    "name": "Amnis Nucum",
    "description": "Fight for a strategic town nestled along a fertile riverbed. Created by Discord user Peanut.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "road-to-amnis-nucum": {
    "name": "Road to Amnis Nucum",
    "description": "This is the main trading road to the major city of Amnis Nucum, situated in the Nucum valley. The road to the valley is filled with harsh mountainous terrain, with a few villages scattered around, and the town of Ga'and overlooking the valley. Created by Discord user Tomsa116.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "aestate-villas": {
    "name": "Aestate Villas",
    "description": "Created by Heated56.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "citta-dei-falchi": {
    "name": "Città Dei Falchi",
    "description": "Use the city in the valley and the strategic hills to outflank and destroy your enemy.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1700,
      "height": 1300
    }
  },
  "rural-alpine": {
    "name": "Rural Alpine",
    "description": "Created by Discord user PEANUT.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "mediterranea-nucum": {
    "name": "Mediterranea Nucum",
    "description": "Outmaneuver your enemy in a battle amidst rolling hills in the hinterland. Created by Discord user PEANUT.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "falkenhugel": {
    "name": "Falkenhugel",
    "description": "Secure a critical road junction nestled among the villages of a once-quiet valley. Created by Discord user Hawke.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 1504,
      "height": 1312
    }
  },
  "grobes-schlachtfeld": {
    "name": "Großes Schlachtfeld",
    "description": "A huge, winding battlefield fit for whole armies to clash. Created by Discord user MooPro.",
    "ranked": false,
    "hidden": false,
    "playerCount": null,
    "mapSize": {
      "width": 2200,
      "height": 1800
    }
  },
  "antioch": {
    "name": "Antioch",
    "description": "Created by shinse1",
    "ranked": false,
    "hidden": false,
    "playerCount": 5,
    "mapSize": {
      "width": 2500,
      "height": 2200
    }
  },
  "waterloo": {
    "name": "Battle of Waterloo",
    "description": "A historical battle fought in 1815, marking the end of the Napoleonic Wars.\nMap made by Codz and Incerus",
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 2944,
      "height": 1872
    }
  },
  "leipzig": {
    "name": "Battle of Leipzig",
    "description": "The first day of the Battle of Leipzig in 1813. Map is created by user: Arethanism. (Discord username is: maggiesmith69) ",
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 4096,
      "height": 2400
    }
  },
  "borodino": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Grand Battle Borodino 1v1",
        "description": "Situation at Borodino 7th September 1812, early morning"
      },
      "ru": {
        "name": "Генеральное сражение Бородино 1v1",
        "description": "Ситуация под Бородино, 7 сентября 1812 года, раннее утро"
      },
      "ar": {
        "name": "المعركة الكبرى بورودينو 1v1",
        "description": "الوضع في بورودينو، 7 سبتمبر 1812، الصباح الباكر"
      },
      "de": {
        "name": "Große Schlacht Borodino 1v1",
        "description": "Die Lage bei Borodino, 7. September 1812, am frühen Morgen"
      },
      "el": {
        "name": "Μεγάλη Μάχη Μποροντινό 1v1",
        "description": "Η κατάσταση στο Μποροντινό, 7 Σεπτεμβρίου 1812, νωρίς το πρωί"
      },
      "es": {
        "name": "Gran Batalla Borodinó 1v1",
        "description": "La situación en Borodinó, 7 de septiembre de 1812, a primera hora de la mañana"
      },
      "fr": {
        "name": "Grande Bataille Borodino 1v1",
        "description": "La situation à Borodino, le 7 septembre 1812, au petit matin"
      },
      "hi": {
        "name": "महान लड़ाई बोरोदिनो 1v1",
        "description": "बोरोदिनो में स्थिति, 7 सितंबर 1812, सुबह तड़के"
      },
      "hu": {
        "name": "Nagy Csata Borogyino 1v1",
        "description": "A helyzet Borogyinónál, 1812. szeptember 7-én, kora reggel"
      },
      "id": {
        "name": "Pertempuran Besar Borodino 1v1",
        "description": "Situasi di Borodino, 7 September 1812, pagi-pagi sekali"
      },
      "it": {
        "name": "Grande Battaglia Borodino 1v1",
        "description": "La situazione a Borodino, 7 settembre 1812, di primo mattino"
      },
      "ja": {
        "name": "グランドバトル ボロジノ 1v1",
        "description": "ボロジノの戦況、1812年9月7日、早朝"
      },
      "kr": {
        "name": "대전투 보로디노 1v1",
        "description": "보로디노의 전황, 1812년 9월 7일, 이른 아침"
      },
      "pl": {
        "name": "Wielka Bitwa Borodino 1v1",
        "description": "Sytuacja pod Borodino, 7 września 1812, wczesnym rankiem"
      },
      "pt": {
        "name": "Grande Batalha Borodino 1v1",
        "description": "A situação em Borodino, 7 de setembro de 1812, de manhã cedo"
      },
      "tr": {
        "name": "Büyük Savaş Borodino 1v1",
        "description": "Borodino'daki durum, 7 Eylül 1812, sabahın erken saatleri"
      },
      "uk": {
        "name": "Велика Битва Бородіно 1v1",
        "description": "Ситуація під Бородіно, 7 вересня 1812 року, рано-вранці"
      },
      "vi": {
        "name": "Trận chiến lớn Borodino 1v1",
        "description": "Tình hình tại Borodino, ngày 7 tháng 9 năm 1812, sáng sớm"
      },
      "zh": {
        "name": "大战役 博罗季诺 1v1",
        "description": "博罗季诺战况，1812年9月7日，清晨"
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 1978,
      "height": 2174
    }
  },
  "combat-at-mollwitz": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Combat at Mollwitz",
        "description": "A historical scenario depicting the Battle of Mollwitz from the First Silesian War, pitting an Austrian relief force (Player 1) against the conquering Prussian (Player 2) army of Frederick II. "
      },
      "ru": {
        "name": "Битва при Мольвице",
        "description": "Исторический сценарий битвы времён Первой Силезской войны, в которой австрийская армия (Игрок 1) противостояла прусской армии Фридриха Великого (Игрок 2)."
      },
      "ar": {
        "name": "القتال في مولويتز",
        "description": "سيناريو تاريخي يصور معركة مولويتز من حرب سيليزيا الأولى ، تأليب قوة إغاثة نمساوية (اللاعب 1) ضد جيش فريدريك الثاني البروسي الفاتح (اللاعب 2)."
      },
      "de": {
        "name": "Schlacht bei Mollwitz",
        "description": "Ein historisches Szenario, das die Schlacht bei Mollwitz aus dem Ersten Schlesischen Krieg darstellt, in der eine österreichische Entsatztruppe (Spieler 1) gegen die erobernde preußische Armee (Spieler 2) Friedrichs II. antritt."
      },
      "el": {
        "name": "Μάχη στο Μόλβιτς",
        "description": "Ένα ιστορικό σενάριο που απεικονίζει τη μάχη του Μόλβιτς από τον πρώτο Σιλεσιανό πόλεμο, αντιπαραθέτοντας μια αυστριακή δύναμη ανακούφισης (Παίκτης 1) εναντίον του κατακτητικού πρωσικού (Παίκτης 2) Στρατού του Φρειδερίκου Β."
      },
      "es": {
        "name": "Combate en Mollwitz",
        "description": "Un escenario histórico que representa la Batalla de Mollwitz de la Primera Guerra de Silesia, enfrentando a una fuerza de socorro austríaca (Jugador 1) contra el ejército conquistador prusiano (Jugador 2) de Federico II."
      },
      "fr": {
        "name": "Combat à Mollwitz",
        "description": "Un scénario historique décrivant la bataille de Mollwitz de la Première Guerre de Silésie, opposant une force de secours autrichienne (Joueur 1) à l'armée prussienne conquérante (Joueur 2) de Frédéric II."
      },
      "hi": {
        "name": "मोलविट्ज़ में मुकाबला",
        "description": "पहला सिलेसियन युद्ध से मोलविट्ज़ की लड़ाई का चित्रण करने वाला एक ऐतिहासिक परिदृश्य, फ्रेडरिक द्वितीय की विजय प्रशिया (खिलाड़ी 1) सेना के खिलाफ एक ऑस्ट्रियाई राहत बल (खिलाड़ी 2) को खड़ा करता है । "
      },
      "hu": {
        "name": "Harc Mollwitznál",
        "description": "Történelmi forgatókönyv, amely a Mollwitzi csata tól első Sziléziai háború, egy osztrák segélyerő (1. játékos) a hódító porosz (2. játékos) hadsereg ellen Frigyes II."
      },
      "id": {
        "name": "Bertempur di Mollwitz",
        "description": "Sebuah skenario sejarah yang menggambarkan Pertempuran Mollwitz dari Perang Silesia Pertama, mengadu pasukan bantuan Austria (Pemain 1) melawan tentara Prusia (Pemain 2) yang menaklukkan Frederick II."
      },
      "it": {
        "name": "Combattimento a Mollwitz",
        "description": "Uno scenario storico raffigurante la battaglia di Mollwitz della prima guerra di Slesia, contrapponendo una forza di soccorso austriaca (Giocatore 1) contro l'esercito prussiano conquistatore (giocatore 2) di Federico II."
      },
      "ja": {
        "name": "モルヴィッツでの戦闘",
        "description": "第一次シレジア戦争からのモルヴィッツの戦いを描いた歴史的なシナリオで、オーストリアの救援部隊（プレーヤー1）を征服したプロイセン軍（プレーヤー2）"
      },
      "kr": {
        "name": "몰비츠 전투",
        "description": "제 1 차 실레시아 전쟁에서 몰비츠 전투를 묘사한 역사적 시나리오로,오스트리아의 구호군(플레이어 1)이 프리드리히 2 세의 정복 프로이센(플레이어 2)군대에 맞서 싸웠다."
      },
      "pl": {
        "name": "Walka w Mollwitz",
        "description": "Historyczny scenariusz bitwy z czasów I wojny Śląskiej, w której armia austriacka (Gracz 1) przeciwstawiła się armii pruskiej Fryderyka Wielkiego (Gracz 2)."
      },
      "pt": {
        "name": "Combate em Mollwitz",
        "description": "Um cenário histórico que descreve a batalha de Mollwitz da Primeira Guerra da Silésia, colocando uma força de Socorro austríaca (Jogador 1) contra o exército prussiano conquistador (Jogador 2) de Frederico II."
      },
      "tr": {
        "name": "Mollwitz Muharebesi",
        "description": "Birinci Silezya Savaşı'nda Mollwitz Muharebesi'ni konu alan tarihi bir senaryo; Avusturya'nın yardım kuvvetlerini (Oyuncu 1) II. Friedrich'in fetheden Prusya ordusuna (Oyuncu 2) karşı karşıya getiriyor."
      },
      "uk": {
        "name": "Битва при Мольвіце",
        "description": "Історичний сценарій, що описує битву при Мольвіце першої Сілезької війни, в якій австрійські допоміжні сили (Гравець 1) протистоять прусській армії Фрідріха II (Гравець 2)."
      },
      "vi": {
        "name": "Chiến đấu Tại Mollwitz",
        "description": "Một kịch bản lịch sử mô tả Trận Mollwitz từ Chiến Tranh Silesian Lần thứ nhất, rỗ một lực lượng cứu Trợ Áo (Người Chơi 1) chống lại quân đội chinh phục Phổ (Người chơi 2) Của Frederick II."
      },
      "zh": {
        "name": "莫尔维茨的战斗",
        "description": "这是一个历史场景，描绘了第一次西里西亚战争中的莫尔维茨战役，一支奥地利救济部队（玩家1）对抗征服普鲁士（玩家2）的弗雷德里克二世军队。"
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 1222,
      "height": 1000
    }
  },
  "clash-at-chelmnitz": {
    "name": "Clash at Chelmnitz",
    "description": "A historically-plausible clash between invading Prussian (Player 1) and defending Saxon (Player 2) forces during the Seven Years War, created by Ulysses-Sockdrawer and slightly edited for competitive play by Hawke. ",
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 1000,
      "height": 1200
    }
  },
  "dresden": {
    "name": "Battle of Dresden",
    "description": "Napoleon's forces clashed with a larger Allied army in a fierce two-day battle in Dresden, Saxony, during the Napoleonic Wars, showcasing intense combat and strategic maneuvering.",
    "ranked": false,
    "hidden": false,
    "playerCount": 2,
    "mapSize": {
      "width": 2787,
      "height": 2412
    }
  },
  "tutorial": {
    "name": "name",
    "description": "description",
    "locales": {
      "en": {
        "name": "Tutorial",
        "description": "Learn the game in a full battle."
      },
      "es": {
        "name": "Tutorial",
        "description": "Aprende el juego en una batalla completa."
      },
      "fr": {
        "name": "Tutoriel",
        "description": "Apprenez le jeu dans une bataille complète."
      },
      "de": {
        "name": "Tutorial",
        "description": "Lerne das Spiel in einer vollen Schlacht."
      },
      "ru": {
        "name": "Обучение",
        "description": "Узнайте тонкости игры в полноценном бою!"
      },
      "pt": {
        "name": "Tutorial",
        "description": "Aprenda o jogo em uma batalha completa."
      },
      "it": {
        "name": "Esercitazione",
        "description": "Impara il gioco in una battaglia completa."
      },
      "pl": {
        "name": "Seminarium",
        "description": "Naucz się gry w pełnej bitwie."
      },
      "tr": {
        "name": "öğretici",
        "description": "Oyunu tam bir savaşta öğrenin."
      },
      "uk": {
        "name": "Підручник",
        "description": "Вивчайте гру в повному бою."
      },
      "vi": {
        "name": "Hướng dẫn",
        "description": "Tìm hiểu trò chơi trong một trận chiến đầy đủ."
      },
      "zh": {
        "name": "教程",
        "description": "在全面的战斗中学习游戏。"
      },
      "ja": {
        "name": "チュートリアル",
        "description": "完全な戦闘でゲームを学びましょう。"
      },
      "kr": {
        "name": "지도 시간",
        "description": "전체 전투에서 게임을 배우십시오."
      },
      "ar": {
        "name": "درس تعليمي",
        "description": "تعلم اللعبة في معركة كاملة."
      },
      "hi": {
        "name": "ट्यूटोरियल",
        "description": "पूरी लड़ाई में खेल सीखें।"
      },
      "id": {
        "name": "tutorial",
        "description": "Pelajari permainan dalam pertempuran penuh."
      },
      "hu": {
        "name": "Oktatóanyag",
        "description": "Tanuld meg a játékot teljes csatában."
      },
      "el": {
        "name": "Φροντιστήριο",
        "description": "Μάθετε το παιχνίδι σε μια πλήρη μάχη."
      }
    },
    "ranked": false,
    "hidden": true,
    "playerCount": 2,
    "mapSize": {
      "tilesX": 64,
      "tilesY": 64
    }
  },
  "line-of-battle": {
    "name": "Line of Battle",
    "description": "A symmetric line-of-battle duel on the open sea. Ten players per side, three ships each.",
    "locales": {
      "en": {
        "name": "Line of Battle",
        "description": "A symmetric line-of-battle duel on the open sea. Ten players per side, three ships each."
      },
      "ru": {
        "name": "Линия баталии",
        "description": "Симметричная дуэль линий баталии в открытом море. Десять игроков на сторону, по три корабля у каждого."
      },
      "ar": {
        "name": "خط المعركة",
        "description": "مبارزة متناظرة بين خطّي معركة في عرض البحر. عشرة لاعبين لكل جانب، وثلاث سفن لكل لاعب."
      },
      "de": {
        "name": "Gefechtslinie",
        "description": "Ein symmetrisches Gefechtslinien-Duell auf offener See. Zehn Spieler pro Seite, je drei Schiffe."
      },
      "el": {
        "name": "Γραμμή Μάχης",
        "description": "Μια συμμετρική μονομαχία γραμμών μάχης στην ανοιχτή θάλασσα. Δέκα παίκτες ανά πλευρά, τρία πλοία ο καθένας."
      },
      "es": {
        "name": "Línea de Batalla",
        "description": "Un duelo simétrico de líneas de batalla en mar abierto. Diez jugadores por bando, tres barcos cada uno."
      },
      "fr": {
        "name": "Ligne de Bataille",
        "description": "Un duel symétrique de lignes de bataille en haute mer. Dix joueurs par camp, trois navires chacun."
      },
      "hi": {
        "name": "युद्ध रेखा",
        "description": "खुले समुद्र में युद्ध रेखाओं का सममित द्वंद्व। प्रति पक्ष दस खिलाड़ी, प्रत्येक के तीन जहाज़।"
      },
      "hu": {
        "name": "Csatasor",
        "description": "Szimmetrikus csatasor-párbaj a nyílt tengeren. Oldalanként tíz játékos, fejenként három hajó."
      },
      "id": {
        "name": "Garis Pertempuran",
        "description": "Duel garis pertempuran simetris di laut lepas. Sepuluh pemain per sisi, tiga kapal masing-masing."
      },
      "it": {
        "name": "Linea di Battaglia",
        "description": "Un duello simmetrico di linee di battaglia in mare aperto. Dieci giocatori per parte, tre navi ciascuno."
      },
      "ja": {
        "name": "戦列",
        "description": "外洋での左右対称の戦列対決。1陣営10人、各自3隻。"
      },
      "kr": {
        "name": "전열",
        "description": "외해에서 벌어지는 대칭 전열 대결. 진영당 10명, 각자 3척."
      },
      "pl": {
        "name": "Linia Bojowa",
        "description": "Symetryczny pojedynek linii bojowych na otwartym morzu. Dziesięciu graczy na stronę, po trzy okręty każdy."
      },
      "pt": {
        "name": "Linha de Batalha",
        "description": "Um duelo simétrico de linhas de batalha em mar aberto. Dez jogadores por lado, três navios cada."
      },
      "tr": {
        "name": "Hat Nizamı",
        "description": "Açık denizde simetrik hat nizamı düellosu. Her tarafta on oyuncu, üçer gemi."
      },
      "uk": {
        "name": "Лінія баталії",
        "description": "Симетрична дуель ліній баталії у відкритому морі. Десять гравців на сторону, по три кораблі в кожного."
      },
      "vi": {
        "name": "Hàng Chiến Tuyến",
        "description": "Cuộc đấu hàng chiến tuyến đối xứng trên biển khơi. Mười người chơi mỗi bên, ba tàu mỗi người."
      },
      "zh": {
        "name": "战列线",
        "description": "公海上对称的战列线对决。每方十名玩家，各三艘战舰。"
      }
    },
    "ranked": false,
    "hidden": false,
    "playerCount": 20,
    "mapSize": {
      "width": 1536,
      "height": 1536
    }
  }
};
